services:
  php-vending:
    container_name: vending-php
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
      - ./xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    ports:
      - "80:80"
    depends_on:
      - mysql-vending
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      XDEBUG_MODE: "develop,debug"
      XDEBUG_CONFIG: "client_host=host.docker.internal start_with_request=yes"

  mysql-vending:
    container_name: vending-mysql
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: vending_database
      MYSQL_USER: my_user
      MYSQL_PASSWORD: my_password
      MYSQL_CHARSET: utf8mb4          
      MYSQL_COLLATION: utf8mb4_unicode_ci 
    ports:
      - "3306:3306"
    volumes:
      - database_vending-data:/var/lib/mysql

volumes:
  database_vending-data: